version: "3"
services: 
  es: 
    image: elasticsearch
    ports: 
      - 9200
      - 9300
    restart: always
  environment: 
    - xpack.monitoring.enabled=false
  volumes:  
   - es_data:/usr/share/elasticsearch/data

  kibana: 
    image: kibana
    ports: 
      - 5601
    restart: always
    environment: 
      ELASTICSEARCH_URL: "http://es:9200"
      - xpack.monitoring.enabled=false
