version: "3"
services: 
  es: 
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.4
    volumes:  
      - elastic_data:/usr/share/elasticsearch/data
    ports: 
      - 9200
      - 9300
    restart: always
    environment: 
      - xpack.monitoring.enabled=false
      
  logstash: 
   image: docker.elastic.co/logstash/logstash:5.6.4
   ports:
    - 10514
   restart: always
   environment:
      - xpack.monitoring.enabled=false

  kibana: 
    image: docker.elastic.co/kibana/kibana:5.6.4
    ports: 
      - 5601
    restart: always
    environment:
      - xpack.monitoring.enabled=false
      - ELASTICSEARCH_URL=http://es:9200
   
volumes:
    elastic_data:
     
