services: 
  environment: 
    xpack.monitoring.enabled: false
  es: 
    image: elasticsearch
    ports: 
      - 9200
      - 9300
  kibana: 
    environment: 
      ELASTICSEARCH_URL: "http://es:9200"
      xpack.monitoring.enabled: false
    image: kibana
    ports: 
      - 5601
    restart: always
  restart: always
version: "3"
